version: "3.8"

services:
  clamav:
    image: clamav/clamav:1.3
    container_name: clamav
    restart: unless-stopped
    ports:
      - "3310:3310"   # expose ClamAV daemon port
    volumes:
      - clamav-db:/var/lib/clamav   # persist virus definitions
      - clamav-logs:/var/log/clamav # optional logging
    environment:
      - CLAMD_STARTUP_TIMEOUT=300   # wait up to 5 minutes for clamd socket
    healthcheck:
      test: ["CMD", "clamdscan", "--version"]
      interval: 60s
      timeout: 15s
      retries: 5
    command: >
      /bin/sh -c "
        echo 'Starting ClamAV...';
        freshclam -d --foreground &
        clamd --foreground
      "

volumes:
  clamav-db:
  clamav-logs:
